-- Migration 034: Group Landing Pages
-- Tracks landing pages generated by ChangeAgent (or other external services).
-- Each row records the headline, type, public URL, and generation metadata.

CREATE TABLE group_landing_pages (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  group_id uuid NOT NULL REFERENCES groups(id) ON DELETE CASCADE,
  org_id uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  -- Nullable because landing pages can be generated by external services (ChangeAgent) with no user session
  created_by uuid DEFAULT NULL REFERENCES profiles(id) ON DELETE SET NULL,
  headline text NOT NULL,
  type text NOT NULL CHECK (type IN ('signup', 'donate')),
  public_url text NOT NULL,
  status text NOT NULL DEFAULT 'live' CHECK (status IN ('live', 'archived')),
  project_id uuid DEFAULT NULL,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

ALTER TABLE group_landing_pages ENABLE ROW LEVEL SECURITY;

-- Super admins can fully manage landing pages for their org
CREATE POLICY "Super admins can manage landing pages"
ON group_landing_pages
FOR ALL
USING (is_super_admin() AND org_id = get_my_org_id())
WITH CHECK (is_super_admin() AND org_id = get_my_org_id());

-- All group members can view their group's landing pages
CREATE POLICY "Group members can view landing pages"
ON group_landing_pages
FOR SELECT
USING (group_id = get_my_group_id());

-- Authenticated users can insert landing pages for their group
-- (supports both admin UI and external service inserts via service role)
CREATE POLICY "Authenticated users can insert landing pages"
ON group_landing_pages
FOR INSERT
WITH CHECK (group_id = get_my_group_id());
